source "https://rubygems.org"

gem "rails"
gem "dagger_ruby"
gem "redis"
gem "delayed_job_active_record"
gem "carrierwave"
gem "friendly_id"
gem "paperclip"
gem "nokogiri"
gem "httparty"
gem "faraday"
gem "graphql"
gem "stripe"
gem "pagy"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "sentry-raven"
gem "newrelic_rpm"
gem "figaro"
gem "dotenv-rails"
gem "annotate"
gem "bullet"
gem "rack-mini-profiler"
gem "meta-tags"
gem "sitemap_generator"
gem "rspec-rails"
gem "factory_bot_rails"
gem "faker"
gem "rubocop"
gem "rubocop-rails"
gem "brakeman"
gem "bundler-audit"
gem "simplecov"
gem "webmock"
gem "vcr"
gem "timecop"
gem "shoulda-matchers"
gem "database_cleaner"
gem "selenium-webdriver"
gem "capybara"
gem "webdrivers"
gem "launchy"

# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end
