version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:10"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      github-actions-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      github-actions-major:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"
